name: commodity-forecast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn  # Provides 'sklearn' module
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - statsmodels
  - pip:
      - yfinance
      - transformers
      - torch
